id: P000024
initial_creation_type: ebook
source_metadata:
  title: ༄༅། །མངོན་པར་རྟོགས་པ་རྒྱན་གྱི་འགྲེལ་པ་རྗེ་བཙུན་བྱམས་པའི་ཞལ་ལུང་ཞེས་བྱ་བ་བཞུགས་སོ།
    །
  authors:
  - མཛད་པ་པོ། ཀུན་མཁྱེན་པདྨ་དཀར་པོ།
  layers:
  - book_title
  - author
  - sabche
  id: KS-PK-12
web_metadata:
  title:
    en: The Words of Lord Maitreya:A Commentary on the Ornament of Realization
    bo: མངོན་པར་རྟོགས་པ་རྒྱན་གྱི་འགྲེལ་པ་རྗེ་བཙུན་བྱམས་པའི་ཞལ་ལུང་ཞེས་བྱ་བ་བཞུགས་སོ།
      །
  collection:
    en: Pema Karpo Series–  Book 12
    bo: ཀུན་མཁྱེན་གཞུང་འགྲེལ།–  དེབ། ༡༢
  author:
    en: Kunkhyen Pema Karpo
    bo: ཀུན་མཁྱེན་པདྨ་དཀར་པོ།
  pusblisher:
    en: Gautam Buddha Vihara
    bo: དོན་བརྒྱུད་དཔལ་ལྡན་འབྲུག་པ།
  sku: KS-PK-12
  category:
    en: Prajnaparamita
    bo: ཤེས་ཕྱིན།
  org:
    bo: Timeless Treasuries
    en: མཐའ་ཡས་དཔེ་མཛོད།
  website: http://dharmacloud.tsadra.org
  aquisition_data: '2019-07-18'
  filename: KS-PK-12.epub
  description:
    en: ''
    bo: ''
